[tool.poetry]
name = "dnp"
version = "0.1.0"
description = "Lightweight, Python-native automatic differentiation engine built on NumPy"
authors = ["mseydifaye"]
readme = "README.md"
packages = [{include = "dnp"}]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.21.0"
scipy = "^1.7.0"
matplotlib = "^3.4.0"
networkx = "^2.6.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
